### PR TITLE
chore add wf4 tests

### PR DESCRIPTION
**Pull request by patrickkenney9801**
enable Debug testing on ci

### CODE REVIEW

**Comment by patrickkenney9801** [comment]
@AdityaAtulTewari can you parse that memory leak error?  My best guess it is because we are using CuSP and so I should re-disable sanitizer tests -- maybe we could keep ubsan

**Review by AdityaAtulTewari — APPROVED** [review]

**Comment by AdityaAtulTewari** [comment]
Where we at with this pr?

**Comment by patrickkenney9801** [comment]
> Where we at with this pr?

I have seen the debug pipeline hang -- but it is probably an issue with galois and hopefully not too common

Other than that -- done

**Comment by AdityaAtulTewari** [comment]
Update and merge?

**Pull request merged**
